# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld/service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18helloworld/service.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n\x0fSayHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x10SayHelloResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x12GetNumbersResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\"(\n\x16MultiplyNumbersRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\")\n\x17MultiplyNumbersResponse\x12\x0e\n\x06number\x18\x02 \x01(\x05\x32\xeb\x01\n\nHelloWorld\x12R\n\x08SayHello\x12\x10.SayHelloRequest\x1a\x11.SayHelloResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/helloworld/say-hello\x12=\n\nGetNumbers\x12\x16.google.protobuf.Empty\x1a\x13.GetNumbersResponse\"\x00\x30\x01\x12J\n\x0fMultiplyNumbers\x12\x17.MultiplyNumbersRequest\x1a\x18.MultiplyNumbersResponse\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SAYHELLOREQUEST = _descriptor.Descriptor(
  name='SayHelloRequest',
  full_name='SayHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SayHelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=118,
)


_SAYHELLORESPONSE = _descriptor.Descriptor(
  name='SayHelloResponse',
  full_name='SayHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='SayHelloResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=152,
)


_GETNUMBERSRESPONSE = _descriptor.Descriptor(
  name='GetNumbersResponse',
  full_name='GetNumbersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='GetNumbersResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=190,
)


_MULTIPLYNUMBERSREQUEST = _descriptor.Descriptor(
  name='MultiplyNumbersRequest',
  full_name='MultiplyNumbersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MultiplyNumbersRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=232,
)


_MULTIPLYNUMBERSRESPONSE = _descriptor.Descriptor(
  name='MultiplyNumbersResponse',
  full_name='MultiplyNumbersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MultiplyNumbersResponse.number', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=275,
)

DESCRIPTOR.message_types_by_name['SayHelloRequest'] = _SAYHELLOREQUEST
DESCRIPTOR.message_types_by_name['SayHelloResponse'] = _SAYHELLORESPONSE
DESCRIPTOR.message_types_by_name['GetNumbersResponse'] = _GETNUMBERSRESPONSE
DESCRIPTOR.message_types_by_name['MultiplyNumbersRequest'] = _MULTIPLYNUMBERSREQUEST
DESCRIPTOR.message_types_by_name['MultiplyNumbersResponse'] = _MULTIPLYNUMBERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHelloRequest = _reflection.GeneratedProtocolMessageType('SayHelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLOREQUEST,
  __module__ = 'helloworld.service_pb2'
  # @@protoc_insertion_point(class_scope:SayHelloRequest)
  ))
_sym_db.RegisterMessage(SayHelloRequest)

SayHelloResponse = _reflection.GeneratedProtocolMessageType('SayHelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLORESPONSE,
  __module__ = 'helloworld.service_pb2'
  # @@protoc_insertion_point(class_scope:SayHelloResponse)
  ))
_sym_db.RegisterMessage(SayHelloResponse)

GetNumbersResponse = _reflection.GeneratedProtocolMessageType('GetNumbersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNUMBERSRESPONSE,
  __module__ = 'helloworld.service_pb2'
  # @@protoc_insertion_point(class_scope:GetNumbersResponse)
  ))
_sym_db.RegisterMessage(GetNumbersResponse)

MultiplyNumbersRequest = _reflection.GeneratedProtocolMessageType('MultiplyNumbersRequest', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLYNUMBERSREQUEST,
  __module__ = 'helloworld.service_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyNumbersRequest)
  ))
_sym_db.RegisterMessage(MultiplyNumbersRequest)

MultiplyNumbersResponse = _reflection.GeneratedProtocolMessageType('MultiplyNumbersResponse', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPLYNUMBERSRESPONSE,
  __module__ = 'helloworld.service_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyNumbersResponse)
  ))
_sym_db.RegisterMessage(MultiplyNumbersResponse)



_HELLOWORLD = _descriptor.ServiceDescriptor(
  name='HelloWorld',
  full_name='HelloWorld',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=278,
  serialized_end=513,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='HelloWorld.SayHello',
    index=0,
    containing_service=None,
    input_type=_SAYHELLOREQUEST,
    output_type=_SAYHELLORESPONSE,
    serialized_options=_b('\202\323\344\223\002\033\022\031/api/helloworld/say-hello'),
  ),
  _descriptor.MethodDescriptor(
    name='GetNumbers',
    full_name='HelloWorld.GetNumbers',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GETNUMBERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MultiplyNumbers',
    full_name='HelloWorld.MultiplyNumbers',
    index=2,
    containing_service=None,
    input_type=_MULTIPLYNUMBERSREQUEST,
    output_type=_MULTIPLYNUMBERSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLD)

DESCRIPTOR.services_by_name['HelloWorld'] = _HELLOWORLD

# @@protoc_insertion_point(module_scope)
